[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP server for the Scryfall API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "httpx>=0.27.0"
]
